/**
 * Tests for the reunified playlist hydrate loop.
 *
 * The hydrate loop delegates per-video work to fetchAndStoreVideo using
 * preFetchedDetails so no extra videos.list calls are issued.
 *
 * Acceptance criteria:
 *   1. fetchAndStoreVideo is invoked once per video (delegation works).
 *   2. No videos.list (batchFetchVideoDetails) calls happen during the
 *      per-video transcript pass — details are reused via preFetchedDetails.
 *      This is now asserted EXPLICITLY by spying on globalThis.fetch (which
 *      is the only network seam batchFetchVideoDetails → fetchVideoBatch
 *      exercises). Previously the invariant was guarded only implicitly by
 *      the fact that unknown test IDs would 404 against the real API —
 *      a regression in a fully-mocked CI could have silently re-introduced
 *      per-video calls. ESM namespace exports are frozen in Node 20+, so
 *      mock.method on the videoBatchFetcher module itself is not possible;
 *      fetch is the nearest mutable observation point.
 *   3. Classification errors are routed through classifyTranscriptError
 *      (indirectly: a "No captions" error produces transcript_status='missing').
 *   4. API quota used by the hydrate pass = ceil(N/50) videos.list calls
 *      (0 per-video when preFetchedDetails is supplied).
 *   5. DB rows written via the delegated fetchAndStoreVideo carry channel_id.
 *
 * Uses the `transcriptFetcher` test seam on fetchAndStoreVideo to inject a
 * mock transcript function without needing ESM module mocking.
 */
import { describe, it, before, afterEach } from "node:test";
import { mock } from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import fs from "node:fs";
import os from "node:os";

// Route the singleton DB at require-time to a clean tmp file so getDb() works.
const tmpDbPath = path.join(
  os.tmpdir(),
  `yt-hydrateLoop-${process.pid}-${Date.now()}.db`
);
fs.writeFileSync(tmpDbPath, "");
process.env.YOUTUBE_MCP_DB_PATH = tmpDbPath;

const { initSchema } = await import("../db/schema.js");
const { getDb } = await import("../db/connection.js");
const { fetchAndStoreVideo } = await import("../tools/get-video-details.js");
import type { VideoDetails, Transcript } from "../types.js";

function makeDetails(id: string): VideoDetails {
  return {
    videoId: id,
    title: `Title ${id}`,
    channelId: `UC_${id}`,
    channelTitle: "Test Channel",
    description: "desc",
    publishedAt: "2024-01-01T00:00:00Z",
    thumbnailUrl: "",
    duration: "5m",
    tags: [],
    categoryId: "22",
    statistics: { viewCount: "0", likeCount: "0", commentCount: "0" },
  };
}

function makeTranscript(id: string): Transcript {
  return {
    videoId: id,
    language: "en",
    isAutoGenerated: false,
    segments: [{ text: "hello", start: 0, duration: 1 }],
    fullText: "hello",
  };
}

describe("hydrate loop reunification (delegates to fetchAndStoreVideo)", () => {
  before(() => {
    const db = getDb();
    initSchema(db);
  });

  afterEach(() => {
    mock.restoreAll();
  });

  it("delegates per-video work to fetchAndStoreVideo using preFetchedDetails (no extra videos.list calls)", async () => {
    const videoIds = ["hlv1", "hlv2", "hlv3", "hlv4"];
    const detailsMap = new Map(videoIds.map((id) => [id, makeDetails(id)]));

    // Explicit spy on globalThis.fetch — the only network seam exercised by
    // batchFetchVideoDetails → fetchVideoBatch. Any regression that drops
    // preFetchedDetails handling and re-introduces per-video videos.list
    // calls will now fail loudly because the spy throws, rather than
    // relying on the implicit "real API would 404 on unknown IDs" behavior.
    const fetchSpy = mock.method(
      globalThis,
      "fetch",
      async (_input: RequestInfo | URL, _init?: RequestInit) => {
        throw new Error(
          "globalThis.fetch must NOT be called during the Step 2 transcript pass " +
            "(would indicate batchFetchVideoDetails ran despite preFetchedDetails)"
        );
      }
    );

    // Track transcript-fetcher invocations; controls mixed outcomes.
    const transcriptCalls: string[] = [];
    const mockTranscriptFetcher = async (id: string): Promise<Transcript> => {
      transcriptCalls.push(id);
      if (id === "hlv1" || id === "hlv2") return makeTranscript(id);
      if (id === "hlv3") throw new Error("No captions available");
      throw new Error("Some other transport failure");
    };

    // Simulate the serial hydrate loop (HYDRATE_TRANSCRIPT_CONCURRENCY=1).
    const outcomes = [];
    for (const id of videoIds) {
      const outcome = await fetchAndStoreVideo(id, true, {
        preFetchedDetails: detailsMap.get(id)!,
        source: "get_playlist_items",
        transcriptFetcher: mockTranscriptFetcher,
      });
      outcomes.push(outcome);
    }

    // Assertion 1: fetchAndStoreVideo was effectively invoked once per video.
    assert.strictEqual(outcomes.length, videoIds.length);

    // Assertion 2: transcriptFetcher was called exactly once per video (serial).
    assert.strictEqual(transcriptCalls.length, videoIds.length);
    assert.deepStrictEqual(transcriptCalls, videoIds);

    // Assertion 3: outcomes reflect classification correctly.
    assert.strictEqual(outcomes[0].transcript, "ok");
    assert.strictEqual(outcomes[1].transcript, "ok");
    assert.strictEqual(outcomes[2].transcript, "missing"); // classifier routed
    assert.strictEqual(outcomes[3].transcript, "failed");

    // Assertion 4 (quota invariant): zero videos.list network calls during
    // the Step 2 transcript-fetch loop. Explicit fetch call-count check
    // replaces the prior implicit "unknown IDs would 404 against real API"
    // guard.
    assert.strictEqual(
      fetchSpy.mock.callCount(),
      0,
      "globalThis.fetch must not be invoked when preFetchedDetails is supplied " +
        "(would indicate a per-video videos.list regression)"
    );

    // Assertion 5: DB rows carry channel_id populated from preFetchedDetails.
    const db = getDb();
    for (const id of videoIds) {
      const row = db
        .prepare(
          "SELECT channel_id, transcript_status FROM videos WHERE video_id = ?"
        )
        .get(id) as
        | { channel_id: string | null; transcript_status: string | null }
        | undefined;
      assert.ok(row, `row for ${id} must exist`);
      assert.strictEqual(
        row!.channel_id,
        `UC_${id}`,
        `channel_id must be populated for ${id}`
      );
    }
  });

  it("preserves HYDRATE_TRANSCRIPT_CONCURRENCY=1 (serial ordering)", async () => {
    const { HYDRATE_TRANSCRIPT_CONCURRENCY } = await import(
      "../tools/get-playlist-items.js"
    );
    assert.strictEqual(HYDRATE_TRANSCRIPT_CONCURRENCY, 1);
  });
});
