services:
  youtube-mcp:
    container_name: youtube-mcp
    build: .
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    stdin_open: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:noexec,nosuid,size=10m
