export interface VideoSearchResult {
  videoId: string;
  title: string;
  channelTitle: string;
  description: string;
  publishedAt: string;
  thumbnailUrl: string;
  viewCount?: string;
  likeCount?: string;
}

export interface VideoDetails {
  videoId: string;
  title: string;
  channelId: string | null;
  channelTitle: string;
  description: string;
  publishedAt: string;
  thumbnailUrl: string;
  duration: string;
  tags: string[];
  categoryId: string;
  defaultLanguage?: string;
  statistics: {
    viewCount: string;
    likeCount: string;
    commentCount: string;
  };
}

export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface Transcript {
  videoId: string;
  language: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
  fullText: string;
}

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  kind?: string;
}

export interface YouTubeApiError {
  code: number;
  message: string;
}
