import type { DatabaseSync } from "node:sqlite";
import type { Transcript } from "../../types.js";
import type { TranscriptRow } from "../types.js";

export interface QueryTranscriptsOpts {
  query?: string;
  language?: string;
  limit?: number;
  offset?: number;
}

export function upsertTranscript(db: DatabaseSync, transcript: Transcript): void {
  db.prepare(
    `
    INSERT OR REPLACE INTO transcripts (
      video_id, language, is_auto_generated, full_text, segments_json, saved_at
    ) VALUES (
      @video_id, @language, @is_auto_generated, @full_text, @segments_json, @saved_at
    )
  `
  ).run({
    video_id: transcript.videoId,
    language: transcript.language,
    is_auto_generated: transcript.isAutoGenerated ? 1 : 0,
    full_text: transcript.fullText ?? null,
    segments_json: transcript.segments ? JSON.stringify(transcript.segments) : null,
    saved_at: new Date().toISOString(),
  });
}

/**
 * Query saved transcripts by full-text LIKE match and optional language.
 */
export function queryTranscripts(
  db: DatabaseSync,
  opts: QueryTranscriptsOpts = {}
): TranscriptRow[] {
  const { query, language, limit = 10, offset = 0 } = opts;

  const conditions: string[] = [];
  const params: unknown[] = [];

  if (query) {
    conditions.push("full_text LIKE ?");
    params.push(`%${query}%`);
  }
  if (language) {
    conditions.push("language = ?");
    params.push(language);
  }

  const where = conditions.length ? `WHERE ${conditions.join(" AND ")}` : "";
  params.push(limit, offset);

  return db
    .prepare(
      `
    SELECT * FROM transcripts
    ${where}
    ORDER BY saved_at DESC
    LIMIT ? OFFSET ?
  `
    )
    .all(...(params as never[])) as unknown as TranscriptRow[];
}

export function getTranscriptByVideoId(
  db: DatabaseSync,
  videoId: string,
  language?: string
): TranscriptRow | null {
  if (language) {
    const row = db
      .prepare(
        "SELECT * FROM transcripts WHERE video_id = ? AND language = ? LIMIT 1"
      )
      .get(videoId, language) as unknown as TranscriptRow | undefined;
    return row ?? null;
  }
  const row = db
    .prepare(
      "SELECT * FROM transcripts WHERE video_id = ? ORDER BY is_auto_generated ASC, saved_at DESC LIMIT 1"
    )
    .get(videoId) as unknown as TranscriptRow | undefined;
  return row ?? null;
}
