import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { fetchTranscript, listAvailableLanguages } from "../services/transcript.js";
import { getDb } from "../db/connection.js";
import { upsertTranscript } from "../db/repos/transcripts.js";

function formatTimestamp(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) {
    return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  }
  return `${m}:${String(s).padStart(2, "0")}`;
}

export function registerGetTranscriptTool(server: McpServer): void {
  server.tool(
    "get_transcript",
    "Fetch the transcript/captions of a YouTube video. Supports language selection and optional timestamps.",
    {
      videoId: z.string().describe("YouTube video ID or full URL"),
      language: z
        .string()
        .optional()
        .describe(
          "Language code (e.g. 'en', 'es'). Omit to use the best available."
        ),
      includeTimestamps: z
        .boolean()
        .default(true)
        .describe("Include [MM:SS] timestamps before each segment"),
      listLanguages: z
        .boolean()
        .default(false)
        .describe(
          "If true, list available languages instead of fetching transcript"
        ),
    },
    async ({ videoId, language, includeTimestamps, listLanguages }) => {
      if (listLanguages) {
        const languages = await listAvailableLanguages(videoId);
        const formatted = languages
          .map(
            (l) =>
              `  ${l.code} - ${l.name}${l.isAutoGenerated && !l.name.includes("auto") ? " (auto-generated)" : ""}`
          )
          .join("\n");
        return {
          content: [
            {
              type: "text",
              text: `Available languages:\n${formatted}`,
            },
          ],
        };
      }

      const transcript = await fetchTranscript(videoId, language);

      try {
        upsertTranscript(getDb(), transcript);
      } catch (err) {
        process.stderr.write(
          `youtube-mcp: DB upsert failed (get_transcript): ${err}\n`
        );
      }

      const header = [
        `Transcript for video: ${transcript.videoId}`,
        `Language: ${transcript.language}${transcript.isAutoGenerated ? " (auto-generated)" : " (manual)"}`,
        `Segments: ${transcript.segments.length}`,
        `---`,
      ].join("\n");

      let body: string;
      if (includeTimestamps) {
        body = transcript.segments
          .map((s) => `[${formatTimestamp(s.start)}] ${s.text}`)
          .join("\n");
      } else {
        body = transcript.fullText;
      }

      return {
        content: [{ type: "text", text: `${header}\n${body}` }],
      };
    }
  );
}
