import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { getVideoDetails } from "../services/youtube-api.js";
import { fetchTranscript } from "../services/transcript.js";

const STOP_WORDS = new Set([
  "the", "a", "an", "is", "are", "was", "were", "be", "been", "being",
  "have", "has", "had", "do", "does", "did", "will", "would", "could",
  "should", "may", "might", "shall", "can", "need", "dare", "ought",
  "used", "to", "of", "in", "for", "on", "with", "at", "by", "from",
  "as", "into", "through", "during", "before", "after", "above", "below",
  "between", "out", "off", "over", "under", "again", "further", "then",
  "once", "here", "there", "when", "where", "why", "how", "all", "both",
  "each", "few", "more", "most", "other", "some", "such", "no", "nor",
  "not", "only", "own", "same", "so", "than", "too", "very", "just",
  "because", "but", "and", "or", "if", "while", "about", "up", "it",
  "its", "this", "that", "these", "those", "i", "me", "my", "we", "our",
  "you", "your", "he", "him", "his", "she", "her", "they", "them",
  "their", "what", "which", "who", "whom", "thing", "things", "like",
  "going", "get", "got", "know", "think", "well", "also", "really",
  "right", "much", "even", "back", "still", "way", "take", "make",
  "come", "go", "see", "look", "want", "give", "use", "said", "say",
  "one", "two", "new", "now", "people", "time", "dont", "im", "ive",
]);

function extractKeyTopics(text: string, topN: number = 8): string[] {
  const words = text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .split(/\s+/)
    .filter((w) => w.length > 3 && !STOP_WORDS.has(w));

  const freq = new Map<string, number>();
  for (const word of words) {
    freq.set(word, (freq.get(word) ?? 0) + 1);
  }

  return [...freq.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, topN)
    .map(([word]) => word);
}

function formatTimestamp(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) {
    return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  }
  return `${m}:${String(s).padStart(2, "0")}`;
}

export function registerSummarizeVideoTool(server: McpServer): void {
  server.tool(
    "summarize_video",
    "Fetch a video's transcript and produce a structured summary with key topics, timestamped sections, and main points. Useful for quickly understanding video content.",
    {
      videoId: z.string().describe("YouTube video ID or full URL"),
      language: z
        .string()
        .optional()
        .describe("Transcript language code (e.g. 'en')"),
    },
    async ({ videoId, language }) => {
      const [details, transcript] = await Promise.all([
        getVideoDetails(videoId),
        fetchTranscript(videoId, language),
      ]);

      const keyTopics = extractKeyTopics(transcript.fullText);

      // Chunk transcript into ~2 minute sections
      const chunkDuration = 120;
      const chunks: { timestamp: string; text: string }[] = [];
      let currentChunkStart = 0;
      let currentTexts: string[] = [];

      for (const segment of transcript.segments) {
        if (
          segment.start >= currentChunkStart + chunkDuration &&
          currentTexts.length > 0
        ) {
          chunks.push({
            timestamp: formatTimestamp(currentChunkStart),
            text: currentTexts.join(" "),
          });
          currentChunkStart = segment.start;
          currentTexts = [];
        }
        currentTexts.push(segment.text);
      }
      if (currentTexts.length > 0) {
        chunks.push({
          timestamp: formatTimestamp(currentChunkStart),
          text: currentTexts.join(" "),
        });
      }

      // Extract first sentence from each chunk as a main point
      const mainPoints = chunks.map((chunk) => {
        const firstSentence =
          chunk.text.match(/^[^.!?]+[.!?]/)?.[0] ?? chunk.text.slice(0, 150);
        return {
          timestamp: chunk.timestamp,
          point: firstSentence.trim(),
        };
      });

      const views = Number(details.statistics.viewCount).toLocaleString();

      const output = [
        `# Video Summary`,
        ``,
        `**${details.title}**`,
        `Channel: ${details.channelTitle} | Duration: ${details.duration} | Views: ${views}`,
        `URL: https://youtube.com/watch?v=${details.videoId}`,
        `Transcript language: ${transcript.language}${transcript.isAutoGenerated ? " (auto-generated)" : ""}`,
        ``,
        `## Key Topics`,
        keyTopics.map((t) => `- ${t}`).join("\n"),
        ``,
        `## Timestamped Sections (${chunks.length} sections)`,
        ...mainPoints.map((p) => `- [${p.timestamp}] ${p.point}`),
        ``,
        `## Full Transcript Preview`,
        transcript.fullText.slice(0, 1000) +
          (transcript.fullText.length > 1000 ? "..." : ""),
        ``,
        `---`,
        `Total transcript length: ${transcript.fullText.length} characters, ${transcript.segments.length} segments`,
      ].join("\n");

      return { content: [{ type: "text", text: output }] };
    }
  );
}
